#ifndef DOORNOTIFY_CONFIG_H
#define DOORNOTIFY_CONFIG_H

#define MQTT_SERVER_URI "tcp://192.168.0.3:1883"
#define MQTT_TOPIC_DOORBELL "esp8266/doorbell/1"
#define MQTT_TOPIC_DOOROPEN "esp8266/dooropen/1"

#endif //DOORNOTIFY_CONFIG_H
